Fix typos
Change-Id: I1b79005d9c4e32325b8dadcc4f805975d6bf2727
Reviewed-on: https://gerrit.libreoffice.org/21103
Reviewed-by: Andras Timar <andras.timar@collabora.com>
Tested-by: Andras Timar <andras.timar@collabora.com>

diff --git a/bin/fuzzfiles b/bin/fuzzfiles
--- a/bin/fuzzfiles
+++ b/bin/fuzzfiles
@@ -10,7 +10,7 @@
 #check that zzuf is installed
 hash zzuf &> /dev/null
 if [ $? -eq 1 ];then
-    echo >&2 "zzuf not found. Please install and/or fix the PATH environement variable. Aborting"
+    echo >&2 "zzuf not found. Please install and/or fix the PATH environment variable. Aborting"
     exit -1
 fi
 
