license header, remove useless comments, usage hint
Change-Id: I33151ffb6b73e2c436da91f275b668e0cb9a31b7

diff --git a/bin/pack-debug b/bin/pack-debug
--- a/bin/pack-debug
+++ b/bin/pack-debug
@@ -1,18 +1,23 @@
-#!/bin/sh
+#!/bin/bash
+#
+# This file is part of the LibreOffice project.
+#
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at http://mozilla.org/MPL/2.0/.
+#
 # create debuginfo and debugsource packages from LO rpm & deb files
 # (generated by using --enable-symbols)
-#
-# Usage:
-#
-# cd /opt/lo_installation_path
-# dbg_pkg
-# # or
-# # PACKAGENAME=collaboraoffice5.1 dbg_pkg # if building in a different path
 
 # build path
 export BUILD_PATH=$PWD
 
 # set install dirname and product version
+if [ ! -f config.log ]; then
+    echo "config.log not found. Run this script from build root."
+    exit 1;
+fi
+
 eval $(grep ^INSTALLDIRNAME config.log)
 eval $(grep ^PRODUCTVERSION config.log)
 
@@ -35,8 +40,6 @@ export build_cpu
 
 #########################################
 # create source package
-# (use PACKAGENAME environmental variable
-# to find "$PACKAGENAME".spec.log)
 #########################################
 
 DEBUGSRC="$(find workdir -name ${DEBUGSRC_PACKAGENAME}.spec.log)"
@@ -171,8 +174,6 @@ function repack_deb {
 
 #########################################
 # create deb source package
-# (use PACKAGENAME environmental variable
-# to find "$PACKAGENAME".spec.log)
 #########################################
 
 DEBUGSRC=$BUILD_PATH/workdir/installation/CollaboraOffice/deb/listfile/en-US/epm_gid_Module_Root_Brand.lst
