bin/run: fix indentation
Change-Id: I97d58f0e6780986356479279f91eba46951b1be0

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -11,68 +11,70 @@
 
 if uname | grep -i CYGWIN >/dev/null; then
 
-dir=$(realpath "$(pwd)")
+    dir=$(realpath "$(pwd)")
 
-while test ! -d "${dir}/instdir/program" ; do
-    if test "${dir}" = "/"; then
-        echo "error: cannot find \"program\" dir from \"$(pwd)\""
-        exit 1
-    fi
-    dir=$(realpath "${dir}/..")
-done
+    while test ! -d "${dir}/instdir/program" ; do
+        if test "${dir}" = "/"; then
+            echo "error: cannot find \"program\" dir from \"$(pwd)\""
+            exit 1
+        fi
+        dir=$(realpath "${dir}/..")
+    done
 
-exedir="${dir}"/workdir/LinkTarget/Executable
-export URE_BOOTSTRAP=file:///$(cygpath -m "${dir}")/instdir/program/fundamental.ini
-export PATH=${PATH:+$PATH:}"${dir}"/instdir/program
+    exedir="${dir}"/workdir/LinkTarget/Executable
+    export URE_BOOTSTRAP=file:///$(cygpath -m "${dir}")/instdir/program/fundamental.ini
+    export PATH=${PATH:+$PATH:}"${dir}"/instdir/program
 
-echo "setting URE_BOOTSTRAP to: ${URE_BOOTSTRAP}"
-echo "setting search path to: ${PATH}"
-echo "execing: ${exedir}/$1"
+    echo "setting URE_BOOTSTRAP to: ${URE_BOOTSTRAP}"
+    echo "setting search path to: ${PATH}"
+    echo "execing: ${exedir}/$1"
 
-exec ${LO_TRACE} "${exedir}"/$@
+    exec ${LO_TRACE} "${exedir}"/$@
 
 elif [ $(uname) = Darwin ]; then
 
-dir=$(pwd)
+    dir=$(pwd)
 
-# Get PRODUCTNAME from config_host.mk, LibreOffice or LibreOfficeDev
-eval `grep 'export PRODUCTNAME=' config_host.mk`
+    # Get PRODUCTNAME from config_host.mk, LibreOffice or LibreOfficeDev
+    eval `grep 'export PRODUCTNAME=' config_host.mk`
 
-if [ ! -d "${dir}/instdir/$PRODUCTNAME.app" ]; then
-    echo "error: cannot find \"instdir/$PRODUCTNAME.app\" dir in \"$(pwd)\""
-    exit 1
-fi
+    if [ ! -d "${dir}/instdir/$PRODUCTNAME.app" ]; then
+        echo "error: cannot find \"instdir/$PRODUCTNAME.app\" dir in \"$(pwd)\""
+        exit 1
+    fi
 
-exedir="${dir}"/workdir/LinkTarget/Executable
-export URE_BOOTSTRAP=file://"${dir}"/instdir/$PRODUCTNAME.app/Contents/Resources/fundamentalrc
-export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH:+$DYLD_LIBRARY_PATH:}"${dir}"/instdir/$PRODUCTNAME.app/Contents/Frameworks
+    exedir="${dir}"/workdir/LinkTarget/Executable
+    export URE_BOOTSTRAP=file://"${dir}"/instdir/$PRODUCTNAME.app/Contents/Resources/fundamentalrc
+    export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH:+$DYLD_LIBRARY_PATH:}"${dir}"/instdir/$PRODUCTNAME.app/Contents/Frameworks
 
-echo "setting URE_BOOTSTRAP to: ${URE_BOOTSTRAP}"
-echo "setting search path to: ${DYLD_LIBRARY_PATH}"
-echo "execing: ${exedir}/$1"
+    echo "setting URE_BOOTSTRAP to: ${URE_BOOTSTRAP}"
+    echo "setting search path to: ${DYLD_LIBRARY_PATH}"
+    echo "execing: ${exedir}/$1"
 
-exec ${LO_TRACE} "${exedir}"/$@
+    exec ${LO_TRACE} "${exedir}"/$@
 
 else
 
-dir=$(readlink -f "$(pwd)")
+    dir=$(readlink -f "$(pwd)")
 
-while test ! -d "${dir}/instdir/program" ; do
-    if test "${dir}" = "/"; then
-        echo "error: cannot find \"program\" dir from \"$(pwd)\""
-        exit 1
-    fi
-    dir=$(readlink -f "${dir}/..")
-done
+    while test ! -d "${dir}/instdir/program" ; do
+        if test "${dir}" = "/"; then
+            echo "error: cannot find \"program\" dir from \"$(pwd)\""
+            exit 1
+        fi
+        dir=$(readlink -f "${dir}/..")
+    done
 
-exedir="${dir}"/workdir/LinkTarget/Executable
-export URE_BOOTSTRAP=file://"${dir}"/instdir/program/fundamentalrc
-export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}"${dir}"/instdir/program
+    exedir="${dir}"/workdir/LinkTarget/Executable
+    export URE_BOOTSTRAP=file://"${dir}"/instdir/program/fundamentalrc
+    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}"${dir}"/instdir/program
 
-echo "setting URE_BOOTSTRAP to: ${URE_BOOTSTRAP}"
-echo "setting search path to: ${LD_LIBRARY_PATH}"
-echo "execing: ${exedir}/$1"
+    echo "setting URE_BOOTSTRAP to: ${URE_BOOTSTRAP}"
+    echo "setting search path to: ${LD_LIBRARY_PATH}"
+    echo "execing: ${exedir}/$1"
 
-exec ${LO_TRACE} "${exedir}"/$@
+    exec ${LO_TRACE} "${exedir}"/$@
 
 fi
+
+# vi:set shiftwidth=4 expandtab:
