make run: skip unit tests
We now have enough unit tests, that running them before 'make run' takes
about 20 seconds here, which is a real problem for a fast modify-code ->
build -> try-it-out cycle.

There was a reason to make unit tests part of the build (and run)
target: they are fast, so manually trying out coolwsd when they may find
something wrong would be a waste of developer time.

Fix the problem by not running these unit tests as part of 'make run',
but still run them as part of 'make'.

Given that we have recursive make here, do this by introducing a new
COOL_SKIP_UNITTESTS environment variable that the toplevel make can set
and the inner make in test/ can read.

Signed-off-by: Miklos Vajna <vmiklos@collabora.com>
Change-Id: Id489c02707eae493d0a89d347bf01def10170ea8
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/9040
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Mike Kaganski <mike.kaganski@collabora.com>

diff --git a/test/Makefile.am b/test/Makefile.am
--- a/test/Makefile.am
+++ b/test/Makefile.am
@@ -514,16 +514,19 @@ if ENABLE_FUZZERS
 all-local:
 else
 all-local: unittest unithttplib clienttest
-	@echo
-	@echo "Running build-time unit tests.  For more thorough testing, please run 'make check'."
-	@echo "Test output is in `pwd`/test.log and is displayed on failure."
-	@echo
-	@fc-cache "@LO_PATH@"/share/fonts/truetype
-	@UNITTEST=1 ${top_builddir}/test/clienttest --cert-path ${abs_top_srcdir}/etc 2> test.log || (cat test.log && /bin/false)
-	@UNITTEST=1 ${top_builddir}/test/unittest --cert-path ${abs_top_srcdir}/etc 2> test.log || (cat test.log && /bin/false)
-	@UNITTEST=1 ${top_builddir}/test/unithttplib --cert-path ${abs_top_srcdir}/etc 2> test.log || (cat test.log && /bin/false)
-	@echo "Done test all-local"
-	@$(CLEANUP_COMMAND)
+	@if [ -n "$${COOL_SKIP_UNITTESTS}" ]; then \
+	    exit 0; \
+	fi; \
+	echo; \
+	echo "Running build-time unit tests.  For more thorough testing, please run 'make check'."; \
+	echo "Test output is in `pwd`/test.log and is displayed on failure."; \
+	echo; \
+	fc-cache "@LO_PATH@"/share/fonts/truetype; \
+	UNITTEST=1 ${top_builddir}/test/clienttest --cert-path ${abs_top_srcdir}/etc 2> test.log || { cat test.log; exit 1; }; \
+	UNITTEST=1 ${top_builddir}/test/unittest --cert-path ${abs_top_srcdir}/etc 2> test.log || { cat test.log; exit 1; }; \
+	UNITTEST=1 ${top_builddir}/test/unithttplib --cert-path ${abs_top_srcdir}/etc 2> test.log || { cat test.log; exit 1; }; \
+	echo "Done test all-local"; \
+	$(CLEANUP_COMMAND)
 endif
 
 distclean-local:
