CWS-TOOLING: integrate CWS movepsprint 2009-02-27 10:42:24 +0100 pl  r268559 : #i99633# remove X11 build for mac 2009-02-26 16:38:01 +0100 pl  r268535 : #i97898# move psprint to vcl: no more linking psprint 2009-02-26 16:36:35 +0100 pl  r268534 : #i97898# move psprint to vcl: tentative os2 changes 2009-02-26 16:20:36 +0100 pl  r268532 : #i97898# move psprint to vcl: make compile again, round 5 2009-02-26 15:53:12 +0100 pl  r268530 : #i97898# psprint removed 2009-02-26 13:43:40 +0100 pl  r268513 : #i97898# use proper X display in PrintFontManager::initialize 2009-02-26 12:39:05 +0100 pl  r268496 : #i99633# remove unsused header 2009-02-25 19:12:54 +0100 pl  r268467 : #i99633# get rid of special casing for the now discontinued Mac X11 port 2009-02-25 18:25:37 +0100 pl  r268466 : #i97898# move psprint to vcl: make compile again, round 4 2009-02-25 17:38:55 +0100 pl  r268458 : #i97898# move psprint to vcl: make compile again, round 3 2009-02-25 16:55:15 +0100 pl  r268452 : #i97898# move psprint to vcl: remove psp lib from install set 2009-02-25 16:50:25 +0100 pl  r268451 : #i97898# move psprint to vcl: make compile again, round 2 2009-02-25 16:10:50 +0100 pl  r268448 : #i97898# move psprint to vcl: make compile again, round 1 2009-02-25 14:38:12 +0100 pl  r268440 : #i97898# move psprint to vcl: remove references to psprint in solenv 2009-02-25 14:22:22 +0100 pl  r268437 : #i97898# move psprint to vcl, first step: move in svn

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18651,26 +18651,33 @@ fi
 
 
 
-if test  "$_os" = "Darwin"  -a  "x$with_x" != "xyes"  -a  "x$x_includes" = "xNONE"  -a  "x$x_libraries" = "xNONE"; then
-         { echo "$as_me:$LINENO: checking for /System/Library/Frameworks/AppKit.framework" >&5
-echo $ECHO_N "checking for /System/Library/Frameworks/AppKit.framework... $ECHO_C" >&6; }
-   if test -d "/System/Library/Frameworks/AppKit.framework/"; then
-      { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-      x_includes="no_x_includes"
-      x_libraries="no_x_libraries"
-            enable_gtk=no
-      enable_cups=no
-      ENABLE_CUPS=""
-
+if test  "$_os" = "Darwin"; then
+   if test "x$with_x" = "xyes"; then
+      { { echo "$as_me:$LINENO: error: X11 build is no longer supported on MacOSX, please use the native aqua build" >&5
+echo "$as_me: error: X11 build is no longer supported on MacOSX, please use the native aqua build" >&2;}
+   { (exit 1); exit 1; }; }
    else
-      { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-         fi
+      { echo "$as_me:$LINENO: checking for /System/Library/Frameworks/AppKit.framework" >&5
+echo $ECHO_N "checking for /System/Library/Frameworks/AppKit.framework... $ECHO_C" >&6; }
+      if test -d "/System/Library/Frameworks/AppKit.framework/"; then
+         { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+         x_includes="no_x_includes"
+         x_libraries="no_x_libraries"
+                  enable_gtk=no
+         enable_cups=no
+         ENABLE_CUPS=""
+
+      else
+         { { echo "$as_me:$LINENO: error: No AppKit.framewrok found" >&5
+echo "$as_me: error: No AppKit.framewrok found" >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+   fi
 fi
 
 if test "$_os" = "Darwin" -a "x$x_includes" = "xno_x_includes"; then
-   echo "Do Nothing for _os = Darwin and x_includes = no_x_includes"
+   echo "Do Nothing for _os = Darwin"
       :
 elif test "$_os" = "OS2" ; then
    echo "Do Nothing for _os = OS2. Don't check for X11."
