#i107747# allow building against older libxml2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14083,23 +14083,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libxml-2.0 >= 2.7.6" >&5
-echo $ECHO_N "checking for libxml-2.0 >= 2.7.6... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libxml-2.0 >= 2.0" >&5
+echo $ECHO_N "checking for libxml-2.0 >= 2.0... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libxml-2.0 >= 2.7.6" ; then
+        if $PKG_CONFIG --exists "libxml-2.0 >= 2.0" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking LIBXML_CFLAGS" >&5
 echo $ECHO_N "checking LIBXML_CFLAGS... $ECHO_C" >&6
-            LIBXML_CFLAGS=`$PKG_CONFIG --cflags "libxml-2.0 >= 2.7.6"`
+            LIBXML_CFLAGS=`$PKG_CONFIG --cflags "libxml-2.0 >= 2.0"`
             echo "$as_me:$LINENO: result: $LIBXML_CFLAGS" >&5
 echo "${ECHO_T}$LIBXML_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking LIBXML_LIBS" >&5
 echo $ECHO_N "checking LIBXML_LIBS... $ECHO_C" >&6
-            LIBXML_LIBS=`$PKG_CONFIG --libs "libxml-2.0 >= 2.7.6"`
+            LIBXML_LIBS=`$PKG_CONFIG --libs "libxml-2.0 >= 2.0"`
             echo "$as_me:$LINENO: result: $LIBXML_LIBS" >&5
 echo "${ECHO_T}$LIBXML_LIBS" >&6
         else
@@ -14107,7 +14107,7 @@ echo "${ECHO_T}$LIBXML_LIBS" >&6
             LIBXML_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            LIBXML_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxml-2.0 >= 2.7.6"`
+            LIBXML_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxml-2.0 >= 2.0"`
             echo $LIBXML_PKG_ERRORS
         fi
 
@@ -14122,8 +14122,8 @@ echo "${ECHO_T}$LIBXML_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libxml-2.0 >= 2.7.6) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libxml-2.0 >= 2.7.6) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libxml-2.0 >= 2.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxml-2.0 >= 2.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
