make 64-bit shell extensions work, put 64-bit VC runtime in the same dir
Unlike in case of msvcr90.dll, which went to WinSxS, msvcr100.dll is installed
to the "system32" folder. Windows installer automatically replaces it to
SysWOW64. The problem is that this way 64-bit dlls end up in the wrong directory.
They conflict with the 32-bit dlls, and will not be installed. Therefore
64-bit shell extensions will not work, unless the 64-bit VC runtime is
installed from other source. It is not possible to install both 32-bit and
64-bit VC Runtime with merge modules in case of VS 2010 and VS 2012.
For the 64-bit shell extensions, we can install the runtime dlls next to the files.

Change-Id: I47060f8ff764ca1156596139ecbec003f964bc60

diff --git a/download b/download
--- a/download
+++ b/download
@@ -50,14 +50,9 @@ if [ "$COM" = "MSC" -a "$CPUNAME" = "INTEL" ]; then
 fi
 
 if [ "$COM" = "MSC" ]; then
-    if [ "$CPUNAME" = "INTEL" ]; then
-        ver=""
-    else
-        ver="-64"
-    fi
     # use oowintool to copy CRT dlls and manifest
-    if ! ./oowintool --msvc-copy-dlls"$ver" ./external/msvcp ; then
-       echo "oowintool failed to copy CRT"
+    if ! ./oowintool --msvc-copy-dlls-64 ./external/msvcp ; then
+       echo "oowintool failed to copy 64-bit CRT"
        exit 1
     fi
 
@@ -65,11 +60,6 @@ if [ "$COM" = "MSC" ]; then
     if ! ./oowintool --msvc-copy-msms"$ver" ./external/msm"$VCVER" ; then
        echo "oowintool failed to copy merge modules"
        exit 1
-    fi
-    if [ "$CPUNAME" = "INTEL" ]; then
-        if ! ./oowintool --msvc-copy-msms-64 ./external/msm"$VCVER" ; then
-           echo "WARNING: oowintool failed to copy x64 merge modules, installation will lack the 64-bit Explorer extension"
-        fi
     fi
 fi
 
