Generate ssh key based on OpenSSH preference
Use better algorithms for key generation based on the preference of
OpenSSH, obtained from the first row of `ssh -Q key`

Change-Id: I12ebcbb62d0752c94b8c2d5225223ceb69b7fe79

diff --git a/logerrit b/logerrit
--- a/logerrit
+++ b/logerrit
@@ -98,7 +98,14 @@ case "$1" in
 	    echo "Hit enter to generate an ssh key - you will need to enter a pass-phrase"
 	    echo
 	    read -r
-	    ssh-keygen -t rsa -f "$ssh_home/id_rsa" # default type as of OpenSSH 8.1
+        type=$(ssh -Q key|grep -v openssh.com|head -n 1)
+        if [ -z "$type" ]
+        then
+            echo "Could not get available key algorithms from 'ssh -Q key'"
+            exit 1
+        else
+	        ssh-keygen -t "$type" # Use available algorithm based on openssh preference
+        fi
 	fi
     if test -d "$ssh_home"; then
         # order algos based on the PubkeyAcceptedKeyTypes option from OpenSSH 8.1
