INTEGRATION: CWS dmake45 (1.2.2); FILE MERGED 2006/06/22 20:45:42 vq 1.2.2.1: #i66650# Make dmake testsuite more portable. (Usable with Solaris.) Patch by hjs.

diff --git a/dmake/tests/infra-0 b/dmake/tests/infra-0
--- a/dmake/tests/infra-0
+++ b/dmake/tests/infra-0
@@ -13,13 +13,14 @@ trap '{ echo "trapped signal - removing temporary files" ; rm -rf $tmpfiles ; }'
 # Test for "test" programm in path
 which test > /dev/null || { echo "Failure! \"test\" program missing." ; exit 1; } 
 echo "Found \"test\" program."
+test=`which test`
 
 # Test for "echo" programm in path
 which echo  > /dev/null || { echo "Failure! \"echo\" program missing." ; exit 1; }
 echo "Found \"echo\" program."
 
 # Test for dmake program
-test -x "${DMAKEPROG}" || { echo "Failure! \"dmake\" is missing." ; exit 1; }
+${test} -x "${DMAKEPROG}" || { echo "Failure! \"dmake\" is missing." ; exit 1; }
 echo "Found \"dmake\" program."
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
@@ -32,11 +33,12 @@ EOT
 
 ${DMAKEPROG} -r -f $file1
 result=$?
-if test ! -e "${file2}"; then
+if ${test} ! -e "${file2}"; then
   echo "File missing"
   result=1
 fi
 
-test $result -eq 0 && echo "Success - Cleaning up" && rm -f ${tmpfiles}
-test $result -ne 0 && echo "Failure!"
+${test} $result -eq 0 && echo "Success - Cleaning up" && rm -f ${tmpfiles}
+${test} $result -ne 0 && echo "Failure!"
 exit $result
+
