INTEGRATION: CWS cmcfixes38 (1.200.4); FILE MERGED 2007/11/02 11:28:48 cmc 1.200.4.2: #i78807# autodetect JAVA_HOME for 4.2.0 gij 2007/10/15 13:38:36 cmc 1.200.4.1: #i78807# autodetect JAVA_HOME for 4.2.0 gij

diff --git a/config_office/configure b/config_office/configure
--- a/config_office/configure
+++ b/config_office/configure
@@ -9247,9 +9247,13 @@ echo "$as_me: WARNING: EXPERIMENTAL: Kaffe is not a full JDK replacement - some 
 echo "${ECHO_T}checked (gcj)" >&6
         _gij_version=`$JAVAINTERPRETER --version | grep GNU | $SED -e 's@^[^0-9]*@@' -e 's@ .*@@' -e 's@,.*@@'`;
         _gij_longver=`echo $_gij_version | $AWK -F. '{ print \$1*10000+\$2*100+\$3 }'`
-        if test -z "$JAVA_HOME"; then
-            JAVA_HOME=`echo $JAVAINTERPRETER | $SED -n "s,//*bin//*$WITH_JAVA,,p"`
+
+        if test "$_gij_longver" -lt "40200" -a "$_gij_longver" -ge "40100"; then
+            if $JAVAINTERPRETER --version | $EGREP "Red Hat" 2>&1 >/dev/null; then
+                _gij_longver="40200"
+            fi
         fi
+
       elif test `$JAVAINTERPRETER -version 2>&1 | awk '{ print }' | grep -c "BEA"` -gt 0; then
         JDK=bea
 
@@ -9530,7 +9534,59 @@ echo "$as_me: error: $_javadoc_path not found set with_jdk_home" >&2;}
 fi
 
 if test "$SOLAR_JAVA" != ""; then
-    if test "$JDK" != "gcj" -o "$_gij_longver" -ge "40200"; then
+        if test "$JDK" == "gcj" -a -z "$JAVA_HOME"; then
+      if test "x$with_jdk_home" = "x" -a "$_gij_longver" -ge "40200"; then
+        cat > findhome.java <<_ACEOF
+import java.io.File;
+
+class findhome
+{
+    public static void main(String args[])
+    {
+        String jrelocation = System.getProperty("java.home");
+        File jre = new File(jrelocation);
+        System.out.println(jre.getParent());
+    }
+}
+_ACEOF
+        echo "$as_me:$LINENO: checking if javac works" >&5
+echo $ECHO_N "checking if javac works... $ECHO_C" >&6
+        javac_cmd="$JAVACOMPILER findhome.java 1>&2"
+        { (eval echo "$as_me:$LINENO: \"$javac_cmd\"") >&5
+  (eval $javac_cmd) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }
+        if test $? = 0 && test -f ./findhome.class ; then
+          echo "$as_me:$LINENO: result: javac works" >&5
+echo "${ECHO_T}javac works" >&6
+        else
+          echo "configure: javac test failed" >&5
+          cat findhome.java >&5
+          { { echo "$as_me:$LINENO: error: javac does not work - java projects will not build!" >&5
+echo "$as_me: error: javac does not work - java projects will not build!" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+
+        echo "$as_me:$LINENO: checking if gij knows its java.home" >&5
+echo $ECHO_N "checking if gij knows its java.home... $ECHO_C" >&6
+        JAVA_HOME=`$JAVAINTERPRETER findhome`
+        if test $? = 0 && test "$JAVA_HOME" != "" ; then
+          echo "$as_me:$LINENO: result: $JAVA_HOME" >&5
+echo "${ECHO_T}$JAVA_HOME" >&6
+        else
+          echo "configure: java test failed" >&5
+          cat findhome.java >&5
+          { { echo "$as_me:$LINENO: error: gij does not know its java.home - use --with-jdk-home" >&5
+echo "$as_me: error: gij does not know its java.home - use --with-jdk-home" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+      else
+        JAVA_HOME=`echo $JAVAINTERPRETER | $SED -n "s,//*bin//*$WITH_JAVA,,p"`
+      fi
+    fi
+
+        if test "$JDK" != "gcj" -o "$_gij_longver" -ge "40200"; then
       # check if JAVA_HOME was (maybe incorrectly?) set automatically to /usr
       if test "$JAVA_HOME" = "/usr" -a "x$with_jdk_home" = "x"; then
 
