INTEGRATION: CWS geordi2q11 (1.57.4); FILE MERGED 2003/12/15 17:45:57 hr 1.57.4.1: #111934#: join CWS ooo111fix1

diff --git a/config_office/configure.in b/config_office/configure.in
--- a/config_office/configure.in
+++ b/config_office/configure.in
@@ -3,7 +3,7 @@ dnl *     vi:set sw=3 ts=3 et:
 dnl *
 dnl * Name: configure.in
 dnl * Auth: Willem van Dorp, Ross Nicholson, Oisin Boydell - Sun Microsystems Ireland
-dnl * Date: $Date: 2003-12-01 17:39:04 $
+dnl * Date: $Date: 2003-12-17 15:01:13 $
 dnl *
 dnl * Desc: This file serves as input for the GNU autoconf package
 dnl *       in order to create a configure script.
@@ -12,15 +12,15 @@ dnl *       necessary to build OpenOffice.org
 dnl *
 dnl *
 dnl ******************************************************************/
-AC_REVISION( $Revision: 1.57 $ )
+AC_REVISION( $Revision: 1.58 $ )
 AC_PREREQ(2.50)
 AC_INIT()
 echo "$@" >config.parms
 AC_ARG_WITH(gnu-patch,
-[  --with-gnu-patch        Specify location of GNU patch on Solaris
+[  --with-gnu-patch        Specify location of GNU patch on Solaris or FreeBSD
 ],,)
 AC_ARG_WITH(gnu-cp,
-[  --with-gnu-cp           Specify location of GNU cp on Solaris 
+[  --with-gnu-cp           Specify location of GNU cp on Solaris or FreeBSD
 ],,)
 AC_ARG_WITH(gpc,
 [  --without-gpc           *NOT RECOMMENDED*  Removes GPC code from
@@ -35,6 +35,19 @@ AC_ARG_ENABLE(libart,
 ],,)
 AC_ARG_ENABLE(libsn,
 [  --enable-libsn          Enables the use of libstartup-notification
+],,)
+AC_ARG_WITH(fonts,
+[  --without-fonts        Removes Bitstream Vera fonts from
+                          openoffice.org installation set, for people building
+                          for specific distributions where the fonts are known 
+                          to be already available
+],,)
+AC_ARG_ENABLE(mozilla,
+[  --enable-mozilla       OO.o may include a strangely hacked up mozilla
+			  binary for your platform, to build with this
+			  enabled, use this option.
+ 
+                          Usage: --enable-mozilla
 ],,)
 AC_ARG_ENABLE(gcc3,
 [  --enable-gcc3           Deprecated: Now has no effect, checks compiler version
@@ -64,8 +77,14 @@ AC_ARG_ENABLE(cl-standard,
 ],,)
 AC_ARG_ENABLE(static-gtk,
 [  --enable-static-gtk:    Modules that are linked against gtk libraries use
-                          the static libraries instead of the dynmaic ones. 
+                          the static libraries instead of the dynamic ones. 
                           (enables -Bstatic linker flag for gtk libraries)
+],,)
+AC_ARG_ENABLE(rpath,
+[  --disable-rpath:        Disable the use of relative paths in shared libraries
+],,)
+AC_ARG_WITH(system-zlib,
+[  --with-system-zlib      Use zlib already on system
 ],,)
 AC_ARG_WITH(stlport4-home,
 [  --with-stlport4-home    The location that STLport4 is installed in. The STL
@@ -422,8 +441,8 @@ if test -n "$enable_symbols" ; then
 		ENABLE_SYMBOLS="TRUE"
 	else
 		if test "$enable_symbols" = "SMALL" -o "$enable_symbols" = "small"; then
-		      ENABLE_SYMBOLS="SMALL"
-	 	else if test "$enable_symbols" != "no"; then
+			ENABLE_SYMBOLS="SMALL"
+		else if test "$enable_symbols" != "no" ; then
 			echo enable symbols is: $enable_symbols
 			AC_MSG_ERROR([--enable-symbols only accepts yes, TRUE or SMALL as parameter.])
 		  fi
@@ -431,6 +450,16 @@ if test -n "$enable_symbols" ; then
 	fi
 fi
 AC_SUBST(ENABLE_SYMBOLS)
+
+dnl ===================================================================
+dnl Disable rpath in shared libraries?
+dnl ===================================================================
+if test "$enable_rpath" = "no"; then
+   ENABLE_RPATH="no"
+else
+   ENABLE_RPATH="yes"
+fi
+AC_SUBST(ENABLE_RPATH)
 
 dnl ===================================================================
 dnl WINNT uses either 4nt or tcsh, all other O/S use tcsh.
@@ -521,6 +550,11 @@ dnl ===================================================================
 dnl  Checks for c compiler,
 dnl  The check for the c++ compiler is later on.
 dnl ===================================================================
+if test -n "$with_cl_home"; then
+   if test -z "$CC"; then
+      CC="$with_cl_home/bin/cl"
+   fi
+fi
 if test -n "$with_gcc_home"; then
    if test -z "$CC"; then
       CC="$with_gcc_home/bin/gcc"
@@ -549,12 +583,12 @@ if test "$GCC" = "yes"; then
    if test "$_gcc_major" = "3"; then
       USE_GCC3="TRUE"
       if test "$_gcc_longver"  -eq "030203"; then
-		 if test $ENABLE_SYMBOLS -eq "SMALL"; then
+		 if test "$ENABLE_SYMBOLS" -eq "SMALL"; then
            AC_MSG_ERROR([version "$_gcc_version" gives internal error with small.])
 		 fi
       fi
    else
-       AC_MSG_ERROR([found version "$_gcc_version", use version 3+ of the gcc compiler])
+      AC_MSG_ERROR([found version "$_gcc_version", use version 3+ of the gcc compiler])
    fi
    AC_MSG_RESULT([checked (gcc $_gcc_version)])
 fi  
@@ -1187,66 +1221,79 @@ AC_SUBST(SOLAR_JAVA)
 dnl ===================================================================
 dnl Checks for JDK.
 dnl ===================================================================
-JAVA_HOME=; export JAVA_HOME
-if test -z "$with_jdk_home"; then
-   AC_PATH_PROG(JAVAC, javac)
-   AC_PATH_PROG(JAVA, java)
-else
-   _javac_path="$with_jdk_home/bin/javac"
-   dnl Check if there is a java compiler at all.
-   if test -x "$_javac_path"; then
-      JAVAC=$_javac_path
-	else
-		AC_MSG_ERROR([$_javac_path not found set with_jdk_home])
-   fi
-   
-   _java_path="$with_jdk_home/bin/java"
-   dnl Check if there is a java interpreter at all.
-   if test -x "$_java_path"; then
-      JAVA=$_java_path
-	else
-		AC_MSG_ERROR([$_java_path not found set with_jdk_home])
-   fi
-fi
-AC_MSG_CHECKING([the installed JDK])
-if test "$JAVA"; then
-
-   dnl java -version sends output to stderr!
-   if test `$JAVA -version 2>&1 | grep -c "Kaffe"` -gt 0; then
-     
-     dnl Kaffe specific tests
-     KAFFE_VER=`$JAVA -version 2>&1 | $EGREP "  Version:" | $SED -r "s/.*  Version: ([[0-9\.]]*).*/\1/"`
-     if test -z "$KAFFE_VER"; then
-       AC_MSG_ERROR([looks like Kaffe but version detection failed])
-     fi
-     _kaffe_ver=`echo "$KAFFE_VER" | $AWK -F. '{ print (($1 * 100) + $2) * 100 + $3;}'`
-     if test "$_kaffe_ver" -lt 10100; then
-        AC_MSG_ERROR([Kaffe is too old ($KAFFE_VER - $_kaffe_ver), you need at least 1.1.0])
-     fi
-     JDK=kaffe
-     
-     dnl TODO: define some project exclusion variables
-     
-     AC_MSG_RESULT([checked (Kaffe $KAFFE_VER)])
-     AC_MSG_WARN([EXPERIMENTAL: Kaffe is not a full JDK replacement - some projects will fail to compile])
-     echo "EXPERIMENTAL: Kaffe is not a full JDK replacement - some projects will fail to compile" >>warn
+if test "$enable_java" != "no"; then
+   JAVA_HOME=; export JAVA_HOME
+   if test -z "$with_jdk_home"; then
+      AC_PATH_PROG(JAVAC, javac)
+      AC_PATH_PROG(JAVA, java)
    else
-     
-     dnl SUN JDK specific tests
-     _jdk=`$JAVAC -J-version 2>&1 | $AWK -F'"' '{ print \$2 }' | $SED s/[[-A-Za-z]]*//`
-     _jdk_ver=`echo "$_jdk" | $AWK -F. '{ print (($1 * 100) + $2) * 100 + $3;}'`
-
-     if test "$_jdk_ver" -lt 10300; then
-          AC_MSG_ERROR([JDK is too old, you need at least 1.3])
-     fi
-     AC_MSG_RESULT([checked (JDK $_jdk)])
+      _javac_path="$with_jdk_home/bin/javac"
+      dnl Check if there is a java compiler at all.
+      if test -x "$_javac_path"; then
+         JAVAC=$_javac_path
+   	else
+   		AC_MSG_ERROR([$_javac_path not found set with_jdk_home])
+      fi
+      
+      _java_path="$with_jdk_home/bin/java"
+      dnl Check if there is a java interpreter at all.
+      if test -x "$_java_path"; then
+         JAVA=$_java_path
+   	else
+   		AC_MSG_ERROR([$_java_path not found set with_jdk_home])
+      fi
    fi
-   JAVA_HOME=`echo $JAVAC | $SED -n "s,//*bin//*javac,,p"`
+   AC_MSG_CHECKING([the installed JDK])
+   if test "$JAVA"; then
+   
+      dnl java -version sends output to stderr!
+      if test `$JAVA -version 2>&1 | grep -c "Kaffe"` -gt 0; then
+        
+        dnl Kaffe specific tests
+        KAFFE_VER=`$JAVA -version 2>&1 | $EGREP "  Version:" | $SED -r "s/.*  Version: ([[0-9\.]]*).*/\1/"`
+        if test -z "$KAFFE_VER"; then
+          AC_MSG_ERROR([looks like Kaffe but version detection failed])
+        fi
+        _kaffe_ver=`echo "$KAFFE_VER" | $AWK -F. '{ print (($1 * 100) + $2) * 100 + $3;}'`
+        if test "$_kaffe_ver" -lt 10100; then
+           AC_MSG_ERROR([Kaffe is too old ($KAFFE_VER - $_kaffe_ver), you need at least 1.1.0])
+        fi
+        JDK=kaffe
+        
+        dnl TODO: define some project exclusion variables
+        
+        AC_MSG_RESULT([checked (Kaffe $KAFFE_VER)])
+        AC_MSG_WARN([EXPERIMENTAL: Kaffe is not a full JDK replacement - some projects will fail to compile])
+        echo "EXPERIMENTAL: Kaffe is not a full JDK replacement - some projects will fail to compile" >>warn
+      else
+        
+        dnl SUN JDK specific tests
+        _jdk=`$JAVAC -J-version 2>&1 | $AWK -F'"' '{ print \$2 }' | $SED s/[[-A-Za-z]]*//`
+        _jdk_ver=`echo "$_jdk" | $AWK -F. '{ print (($1 * 100) + $2) * 100 + $3;}'`
+   
+        if test "$_jdk_ver" -lt 10300; then
+             AC_MSG_ERROR([JDK is too old, you need at least 1.3])
+        fi
+        AC_MSG_RESULT([checked (JDK $_jdk)])
+      fi
+      JAVA_HOME=`echo $JAVAC | $SED -n "s,//*bin//*javac,,p"`
+   else
+      AC_MSG_ERROR([JAVA not found. You need at least jdk-1.3])
+   fi
+   dnl xsltproc not needed with JDK present.
+   XSLTPROC=NO_XSLTPROC
 else
-   AC_MSG_ERROR([JAVA not found. You need at least jdk-1.3])
+   dnl Java disabled
+   JAVA_HOME=NO_JAVA_HOME ; export JAVA_HOME
+   dnl Check for xsltproc
+   AC_PATH_PROG(XSLTPROC, xsltproc, no)
+   if test "$XSLTPROC" = "no"; then
+      AC_MSG_ERROR([xsltproc is required when building with --disable-java.])
+   fi
 fi
 AC_SUBST(JAVA_HOME)
 AC_SUBST(JDK)
+AC_SUBST(XSLTPROC)
 
 dnl ===================================================================
 dnl Checks for specific files.
@@ -1319,6 +1366,46 @@ else
    TCSH="NO_TCSH_NEEDED"
 fi
 AC_SUBST(TCSH)
+
+dnl ===================================================================
+dnl Check whether we already have dmake
+dnl ===================================================================
+AC_PATH_PROG(DMAKE, dmake, no)
+if test "$DMAKE" = "no"; then
+    BUILD_DMAKE=YES
+else
+    AC_MSG_CHECKING([whether the found dmake is the right dmake])
+    # we need to find out whether that dmake we found is "our" dmake
+    # or the dmake from Sun's Workshop Compiler which is something
+    # different
+    # This test _should_ work because the one accepts -V (ours) and one
+    # (the other) not...
+    dmake -V 2>/dev/null | grep 'dmake .* Version 4.*, PL ' >/dev/null
+    if test $? -eq 0; then 
+       BUILD_DMAKE=NO
+       AC_MSG_RESULT([yes])
+    else
+       AC_MSG_RESULT([no])
+       BUILD_DMAKE=YES
+    fi
+fi
+AC_SUBST(BUILD_DMAKE)
+
+dnl ===================================================================
+dnl Check for system zlib
+dnl ===================================================================
+AC_MSG_CHECKING([which zlib to use])
+if test -n "$with_system_zlib"; then
+    AC_MSG_RESULT([external])
+    SYSTEM_ZLIB=YES
+    AC_MSG_CHECKING([for zlib.h])
+    AC_TRY_COMPILE([#include "zlib.h"], [],
+        [AC_MSG_RESULT(found)], [AC_MSG_ERROR(zlib not found. install zlib)])
+else
+    AC_MSG_RESULT([internal])
+    SYSTEM_ZLIB=NO
+fi
+AC_SUBST(SYSTEM_ZLIB)
 
 dnl ===================================================================
 dnl Check whether the gtk 2.0 libraries are available.
@@ -1460,8 +1547,8 @@ if test -z "$PATCH"; then
    AC_MSG_ERROR([\"patch\" not found in \$PATH, install the development tool named\"patch"\])
 fi
 
-dnl On Solaris, check if --with-gnu-patch was used
-if test "$_os" = "SunOS"; then
+dnl On Solaris or FreeBSD, check if --with-gnu-patch was used
+if test "$_os" = "SunOS" -o "$_os" = "FreeBSD"; then
    if test -z "$with_gnu_patch"; then
       GNUPATCH=$PATCH
    else
@@ -1516,7 +1603,7 @@ else
 fi
 ASM_HOME="$with_asm_home"
 AC_SUBST(ASM_HOME)
-
+ 
 dnl ===================================================================
 dnl testing handle deprecated unzip switch
 dnl ===================================================================
@@ -1658,6 +1745,36 @@ AC_SUBST(LIBSN_CFLAGS)
 AC_SUBST(LIBSN_LIBS)
 
 dnl ===================================================================
+dnl Disable mozilla if we can
+dnl ===================================================================
+
+AC_MSG_CHECKING([whether to build mozilla connectivity])
+if test -n "$enable_mozilla"; then
+   AC_MSG_RESULT([yes])
+   WITH_MOZILLA=YES
+else
+   AC_MSG_RESULT([no])
+   WITH_MOZILLA=NO
+   SCPDEFS="$SCPDEFS -DWITHOUT_MOZILLA"
+fi
+AC_SUBST(WITH_MOZILLA)
+
+dnl ===================================================================
+dnl Test whether to include fonts
+dnl ===================================================================
+AC_MSG_CHECKING([whether to include Bitstream Vera fonts])
+if test "$with_fonts" != "no" ; then
+  AC_MSG_RESULT([yes])
+  WITH_FONTS=YES
+else
+  AC_MSG_RESULT([no])
+  WITH_FONTS=NO
+  SCPDEFS="$SCPDEFS -DWITHOUT_FONTS"
+fi
+AC_SUBST(WITH_FONTS)
+AC_SUBST(SCPDEFS)
+
+dnl ===================================================================
 dnl Test for the presence of Ant and that it works
 dnl ===================================================================
 
@@ -1724,6 +1841,8 @@ echo "********************************************************************"
 # Get UPD number from ../solenv/inc/minor.mk
 UPD="`grep RSCVERSION= ../solenv/inc/minor.mk | $AWK -F"=" '{ print $2 }'`"
 AC_SUBST(UPD)
+SOURCEVERSION="`grep SOURCEVERSION= ../solenv/inc/minor.mk | $AWK -F"=" '{ print $2 }'`"
+AC_SUBST(SOURCEVERSION)
 
 if test -z "$COMPATH"; then
    AC_MSG_ERROR([No compiler found.])
