INTEGRATION: CWS dba24c (1.200.10); FILE MERGED 2007/10/30 16:36:30 fs 1.200.10.2: RESYNC: (1.200-1.201); FILE MERGED 2007/10/29 11:04:13 fs 1.200.10.1: #i83079# HSQL 1.8.0.9 is needed by now

diff --git a/config_office/configure b/config_office/configure
--- a/config_office/configure
+++ b/config_office/configure
@@ -13768,8 +13768,8 @@ echo "$as_me: error: hsqldb.jar not found." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-        echo "$as_me:$LINENO: checking whether hsqldb is >= 1.8.0.8" >&5
-echo $ECHO_N "checking whether hsqldb is >= 1.8.0.8... $ECHO_C" >&6
+        { echo "$as_me:$LINENO: checking whether hsqldb is >= 1.8.0.9" >&5
+echo $ECHO_N "checking whether hsqldb is >= 1.8.0.9... $ECHO_C" >&6; }
         export HSQLDB_JAR
         if $PERL -e 'use Archive::Zip;
             my $file = "$ENV{'HSQLDB_JAR'}";
@@ -13782,7 +13782,7 @@ echo $ECHO_N "checking whether hsqldb is >= 1.8.0.8... $ECHO_C" >&6
 		        ($t, $version) = split (/:/,$line);
 		        $version =~ s/^\s//;
 		        ($a, $b, $c, $d) = split (/\./,$version);
-		        if (($c == "0" && $d > "7") || $c > 0)  {
+		        if (($c == "0" && $d > "8") || $c > 0)  {
 		            exit 0;
 		        } else {
 		            exit 1;
@@ -13795,8 +13795,8 @@ echo $ECHO_N "checking whether hsqldb is >= 1.8.0.8... $ECHO_C" >&6
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
          else
-            { { echo "$as_me:$LINENO: error: no, hsqldb >= 1.8.0.8 is needed" >&5
-echo "$as_me: error: no, hsqldb >= 1.8.0.8 is needed" >&2;}
+            { { echo "$as_me:$LINENO: error: no, hsqldb >= 1.8.0.9 is needed" >&5
+echo "$as_me: error: no, hsqldb >= 1.8.0.9 is needed" >&2;}
    { (exit 1); exit 1; }; }
          fi
 else
