INTEGRATION: CWS vq38 (1.165.4); FILE MERGED 2006/10/20 00:48:57 vq 1.165.4.5: #i70353# Switch from ENABLE_STRIP to DISABLE_STRIP. 2006/10/17 22:04:06 vq 1.165.4.4: #i70353# Add missing quotes. 2006/10/17 21:42:51 vq 1.165.4.3: #i70353# Add a new configure switch to controll the stripping of the solver. 2006/10/17 01:17:17 vq 1.165.4.2: #i70353# Decouple --enable-crashdump from --enable-symbols. 2006/10/14 22:32:25 vq 1.165.4.1: #i70432# Rename NETTOOLKIT to DISABLE_ACTIVEX.

diff --git a/config_office/configure b/config_office/configure
--- a/config_office/configure
+++ b/config_office/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS AWK SED LOCAL_SOLENV UPD SOURCEVERSION build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OSVERSION PTHREAD_CFLAGS PTHREAD_LIBS ENABLE_CRASHDUMP VC_STANDARD ENABLE_WERROR ENABLE_DEBUG PRODUCT PROFULLSWITCH PROEXT ENABLE_SYMBOLS ENABLE_CUPS ENABLE_FONTCONFIG WITH_BINFILTER ENABLE_DIRECTX NETTOOLKIT ENABLE_RPATH WITH_MYSPELL_DICTS USE_SHELL WITH_MINGWIN SHELLPATH GCC_HOME CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT COMPATH GCCVER HAVE_GCC_VISIBILITY_FEATURE GNUMAKE _cc PERL MSPDB_PATH COMEX MIDL_PATH CSC_PATH FRAME_HOME CPP EGREP PAM NEW_SHADOW_API PAM_LINK CRYPT_LINK CXX CXXFLAGS ac_ct_CXX GXX_INCLUDE_PATH EXCEPTIONS CXXCPP STLPORT4 USE_SYSTEM_STL ALLOC BUILD_VER_STRING SOLAR_JAVA LANG JAVAINTERPRETER JAVACOMPILER JAVACISGCJ JAVADOC AWTLIB JAVAAOTCOMPILER JAVA_HOME JDK XSLTPROC DMAKE BUILD_DMAKE EPM DPKG PKGMK BUILD_EPM PKGFORMAT RPM MINGWCXX ac_ct_MINGWCXX MINGWSTRIP ac_ct_MINGWSTRIP BUILD_UNOWINREG SYSTEM_STDLIBS SYSTEM_ZLIB SYSTEM_JPEG SYSTEM_EXPAT PKG_CONFIG FREETYPE_CFLAGS FREETYPE_LIBS SYSTEM_FREETYPE LIBWPD_CFLAGS LIBWPD_LIBS SYSTEM_LIBWPD USE_FT_EMBOLDEN LIBXML_CFLAGS LIBXML_LIBS SYSTEM_LIBXML PYTHON PYTHON_VERSION PYTHON_PREFIX PYTHON_EXEC_PREFIX PYTHON_PLATFORM pythondir pkgpythondir pyexecdir pkgpyexecdir SYSTEM_PYTHON PYTHON_CFLAGS PYTHON_LIBS SYSTEM_DB DB_VERSION DB_INCLUDES DB_JAR SYSTEM_HSQLDB HSQLDB_JAR SYSTEM_BSH BSH_JAR SYSTEM_XML_APIS XML_APIS_JAR SYSTEM_XERCES XERCES_JAR SERIALIZER_JAR SYSTEM_XALAN XALAN_JAR SABLOTCONFIG SYSTEM_SABLOT SABLOT_LIBS CURLCONFIG SYSTEM_CURL CURL_CFLAGS CURL_LIBS SYSTEM_BOOST SYSTEM_ODBC_HEADERS WITH_MOZILLA WITH_LDAP WITH_OPENLDAP MOZILLAXPCOM_CFLAGS MOZILLAXPCOM_LIBS MOZ_NSPR_CFLAGS MOZ_NSPR_LIBS NSPR_LIB MOZ_NSS_CFLAGS MOZ_NSS_LIBS NSS_LIB MOZILLA_VERSION MOZILLA_TOOLKIT MOZLIBREQ_CFLAGS MOZLIBREQ_LIBS BUILD_MOZAB SYSTEM_MOZILLA MOZ_FLAVOUR MOZ_INC MOZ_LIB MOZ_LIB_XPCOM MOZ_LDAP_CFLAGS SYSTEM_SANE_HEADER X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS XINC XLIB SYSTEM_XRENDER_HEADERS XRENDER_LINK XMKMF SYSTEM_NAS NAS_INCLUDES ENABLE_NAS ENABLE_PASF SYSTEM_PORTAUDIO SYSTEM_SNDFILE BUILD_TYPE DISABLE_NEON NEON_CFLAGS NEON_LIBS SYSTEM_NEON NEON_VERSION ENABLE_AGG AGG_CFLAGS AGG_LIBS SYSTEM_AGG AGG_VERSION MYSPELL_CFLAGS MYSPELL_LIBS SYSTEM_MYSPELL SYSTEM_HUNSPELL HUNSPELL_CFLAGS SYSTEM_HYPH SYSTEM_MYTHES PSDK_HOME DIRECTXSDK_HOME DIRECTXSDK_LIB NSIS_PATH BISON FLEX PATCH GNUPATCH GNUCP CYGWIN_PATH ML_EXE ASM_HOME ZIP UNZIP ZIP_HOME WITH_GPC ENABLE_GTK ENABLE_KDE GNOMEVFS_CFLAGS GNOMEVFS_LIBS GCONF_CFLAGS GCONF_LIBS ENABLE_GNOMEVFS GTK_CFLAGS GTK_LIBS GDKPIXBUF_CFLAGS GDKPIXBUF_LIBS CAIRO_CFLAGS CAIRO_LIBS ENABLE_CAIRO SYSTEM_CAIRO MOC KDE_CFLAGS KDE_LIBS ENABLE_LOCKDOWN LIBSN_CFLAGS LIBSN_LIBS WITH_LIBSN GOBJECT_CFLAGS GOBJECT_LIBS ENABLE_EVOAB2 ENABLE_KAB WITH_FONTOOO SYSTEM_MSPACK WITH_FONTS SCPDEFS WITHOUT_PPDS WITHOUT_AFMS USE_XINERAMA XINERAMA_LINK ANT ANT_HOME ANT_LIB WITH_LANG WITH_DICT ENABLE_STATIC_GTK ENABLE_JAM LOCAL_SOLVER LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS AWK SED LOCAL_SOLENV UPD SOURCEVERSION build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os OSVERSION PTHREAD_CFLAGS PTHREAD_LIBS ENABLE_CRASHDUMP VC_STANDARD ENABLE_WERROR ENABLE_DEBUG PRODUCT PROFULLSWITCH PROEXT ENABLE_SYMBOLS DISABLE_STRIP ENABLE_CUPS ENABLE_FONTCONFIG WITH_BINFILTER ENABLE_DIRECTX DISABLE_ACTIVEX ENABLE_RPATH WITH_MYSPELL_DICTS USE_SHELL WITH_MINGWIN SHELLPATH GCC_HOME CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT COMPATH GCCVER HAVE_GCC_VISIBILITY_FEATURE GNUMAKE _cc PERL MSPDB_PATH COMEX MIDL_PATH CSC_PATH FRAME_HOME CPP EGREP PAM NEW_SHADOW_API PAM_LINK CRYPT_LINK CXX CXXFLAGS ac_ct_CXX GXX_INCLUDE_PATH EXCEPTIONS CXXCPP STLPORT4 USE_SYSTEM_STL ALLOC BUILD_VER_STRING SOLAR_JAVA LANG JAVAINTERPRETER JAVACOMPILER JAVACISGCJ JAVADOC AWTLIB JAVAAOTCOMPILER JAVA_HOME JDK XSLTPROC DMAKE BUILD_DMAKE EPM DPKG PKGMK BUILD_EPM PKGFORMAT RPM MINGWCXX ac_ct_MINGWCXX MINGWSTRIP ac_ct_MINGWSTRIP BUILD_UNOWINREG SYSTEM_STDLIBS SYSTEM_ZLIB SYSTEM_JPEG SYSTEM_EXPAT PKG_CONFIG FREETYPE_CFLAGS FREETYPE_LIBS SYSTEM_FREETYPE LIBWPD_CFLAGS LIBWPD_LIBS SYSTEM_LIBWPD USE_FT_EMBOLDEN LIBXML_CFLAGS LIBXML_LIBS SYSTEM_LIBXML PYTHON PYTHON_VERSION PYTHON_PREFIX PYTHON_EXEC_PREFIX PYTHON_PLATFORM pythondir pkgpythondir pyexecdir pkgpyexecdir SYSTEM_PYTHON PYTHON_CFLAGS PYTHON_LIBS SYSTEM_DB DB_VERSION DB_INCLUDES DB_JAR SYSTEM_HSQLDB HSQLDB_JAR SYSTEM_BSH BSH_JAR SYSTEM_XML_APIS XML_APIS_JAR SYSTEM_XERCES XERCES_JAR SERIALIZER_JAR SYSTEM_XALAN XALAN_JAR SABLOTCONFIG SYSTEM_SABLOT SABLOT_LIBS CURLCONFIG SYSTEM_CURL CURL_CFLAGS CURL_LIBS SYSTEM_BOOST SYSTEM_ODBC_HEADERS WITH_MOZILLA WITH_LDAP WITH_OPENLDAP MOZILLAXPCOM_CFLAGS MOZILLAXPCOM_LIBS MOZ_NSPR_CFLAGS MOZ_NSPR_LIBS NSPR_LIB MOZ_NSS_CFLAGS MOZ_NSS_LIBS NSS_LIB MOZILLA_VERSION MOZILLA_TOOLKIT MOZLIBREQ_CFLAGS MOZLIBREQ_LIBS BUILD_MOZAB SYSTEM_MOZILLA MOZ_FLAVOUR MOZ_INC MOZ_LIB MOZ_LIB_XPCOM MOZ_LDAP_CFLAGS SYSTEM_SANE_HEADER X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS XINC XLIB SYSTEM_XRENDER_HEADERS XRENDER_LINK XMKMF SYSTEM_NAS NAS_INCLUDES ENABLE_NAS ENABLE_PASF SYSTEM_PORTAUDIO SYSTEM_SNDFILE BUILD_TYPE DISABLE_NEON NEON_CFLAGS NEON_LIBS SYSTEM_NEON NEON_VERSION ENABLE_AGG AGG_CFLAGS AGG_LIBS SYSTEM_AGG AGG_VERSION MYSPELL_CFLAGS MYSPELL_LIBS SYSTEM_MYSPELL SYSTEM_HUNSPELL HUNSPELL_CFLAGS SYSTEM_HYPH SYSTEM_MYTHES PSDK_HOME DIRECTXSDK_HOME DIRECTXSDK_LIB NSIS_PATH BISON FLEX PATCH GNUPATCH GNUCP CYGWIN_PATH ML_EXE ASM_HOME ZIP UNZIP ZIP_HOME WITH_GPC ENABLE_GTK ENABLE_KDE GNOMEVFS_CFLAGS GNOMEVFS_LIBS GCONF_CFLAGS GCONF_LIBS ENABLE_GNOMEVFS GTK_CFLAGS GTK_LIBS GDKPIXBUF_CFLAGS GDKPIXBUF_LIBS CAIRO_CFLAGS CAIRO_LIBS ENABLE_CAIRO SYSTEM_CAIRO MOC KDE_CFLAGS KDE_LIBS ENABLE_LOCKDOWN LIBSN_CFLAGS LIBSN_LIBS WITH_LIBSN GOBJECT_CFLAGS GOBJECT_LIBS ENABLE_EVOAB2 ENABLE_KAB WITH_FONTOOO SYSTEM_MSPACK WITH_FONTS SCPDEFS WITHOUT_PPDS WITHOUT_AFMS USE_XINERAMA XINERAMA_LINK ANT ANT_HOME ANT_LIB WITH_LANG WITH_DICT ENABLE_STATIC_GTK ENABLE_JAM LOCAL_SOLVER LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -903,12 +903,20 @@ Optional Features:
                           This switch is mandatory when using VC++ 2005 Express.
 
   --enable-symbols        Include debugging symbols in output.
-                          Implicitly activated by --enable-crashdump (see below)
                           WARNING - a complete build needs 8 Gb of space and
                           takes much longer. (enables -g compiler flag)
 
                           --enable-symbols=SMALL sets the gcc -g1 setting
                           which is smaller.
+
+                          Enabling symbols disables the stripping of the solver
+                          (--disable-strip-solver).
+
+  --disable-strip-solver  Disable the stripping of the solver.
+                          By default the solver is stripped unless a build with
+                          debugging symbols (--enable-symbols) is requested.
+
+                          This switch allows to override this setting.
 
   --enable-werror         Turn warnings to errors. (Has no effect in modules where
                           the treating of warnings as errors is disabled explicitely)
@@ -925,8 +933,6 @@ Optional Features:
 
   --enable-crashdump[=yes|TRUE|STATIC|no]
                           Enable (disable) the crashdump feature code. [default=no]
-                          When enabled, this option implicitly
-                          activates --enable-symbols (see above).
 
   --enable-cl-standard    For Microsoft C/C++ compiler users, use non-optimizing
                           standard compiler. ( This just disavles optimization
@@ -1921,6 +1927,11 @@ fi;
 # Check whether --enable-symbols or --disable-symbols was given.
 if test "${enable_symbols+set}" = set; then
   enableval="$enable_symbols"
+
+fi;
+# Check whether --enable-strip-solver or --disable-strip-solver was given.
+if test "${enable_strip_solver+set}" = set; then
+  enableval="$enable_strip_solver"
 
 fi;
 # Check whether --enable-werror or --disable-werror was given.
@@ -2945,18 +2956,12 @@ echo "$as_me:$LINENO: checking whether to enable crashdump feature" >&5
 echo $ECHO_N "checking whether to enable crashdump feature... $ECHO_C" >&6
 if test "$enable_crashdump" = "yes" -o "$enable_crashdump" = "TRUE"; then
    ENABLE_CRASHDUMP="TRUE"
-   if test -z "$enable_symbols"; then
-      enable_symbols="yes"
-   fi
    echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
    BUILD_TYPE="$BUILD_TYPE CRASHREP"
 else
    if test "$enable_crashdump" = "STATIC"; then
       ENABLE_CRASHDUMP="STATIC"
-      if test -z "$enable_symbols"; then
-         enable_symbols="yes"
-      fi
       echo "$as_me:$LINENO: result: yes, STATIC" >&5
 echo "${ECHO_T}yes, STATIC" >&6
       BUILD_TYPE="$BUILD_TYPE CRASHREP"
@@ -3056,7 +3061,7 @@ echo "${ECHO_T}yes" >&6
 	else
 		if test "$enable_symbols" = "SMALL" -o "$enable_symbols" = "small"; then
 			ENABLE_SYMBOLS="SMALL"
-         echo "$as_me:$LINENO: result: yes, small ones" >&5
+			echo "$as_me:$LINENO: result: yes, small ones" >&5
 echo "${ECHO_T}yes, small ones" >&6
 		else if test "$enable_symbols" != "no" ; then
 			     echo enable symbols is: $enable_symbols
@@ -3072,6 +3077,28 @@ else
    ENABLE_SYMBOLS=
    echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
+fi
+
+
+echo "$as_me:$LINENO: checking whether to strip the solver or not." >&5
+echo $ECHO_N "checking whether to strip the solver or not.... $ECHO_C" >&6
+if test -n "$enable_strip_solver"; then
+   if test "$enable_strip_solver" = "yes"; then
+      DISABLE_STRIP=
+   else if test "$enable_strip_solver" = "no"; then
+           DISABLE_STRIP="TRUE"
+        else
+           { { echo "$as_me:$LINENO: error: --disable-strip-solver only accepts yes or no as parameter." >&5
+echo "$as_me: error: --disable-strip-solver only accepts yes or no as parameter." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+   fi
+else
+   if test -n "$ENABLE_SYMBOLS"; then
+      DISABLE_STRIP="TRUE"
+   else
+      DISABLE_STRIP=
+   fi
 fi
 
 
@@ -3132,11 +3159,11 @@ echo "${ECHO_T}no" >&6
    echo "$as_me:$LINENO: checking whether to use ActiveX" >&5
 echo $ECHO_N "checking whether to use ActiveX... $ECHO_C" >&6
    if test "$enable_activex" = "yes" -o "$enable_activex" = "TRUE" -o "$enable_activex" = ""; then
-         NETTOOLKIT=""
+      DISABLE_ACTIVEX=""
       echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
    else
-      NETTOOLKIT="TRUE"
+      DISABLE_ACTIVEX="TRUE"
       echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
    fi
@@ -22899,11 +22926,12 @@ s,@PRODUCT@,$PRODUCT,;t t
 s,@PROFULLSWITCH@,$PROFULLSWITCH,;t t
 s,@PROEXT@,$PROEXT,;t t
 s,@ENABLE_SYMBOLS@,$ENABLE_SYMBOLS,;t t
+s,@DISABLE_STRIP@,$DISABLE_STRIP,;t t
 s,@ENABLE_CUPS@,$ENABLE_CUPS,;t t
 s,@ENABLE_FONTCONFIG@,$ENABLE_FONTCONFIG,;t t
 s,@WITH_BINFILTER@,$WITH_BINFILTER,;t t
 s,@ENABLE_DIRECTX@,$ENABLE_DIRECTX,;t t
-s,@NETTOOLKIT@,$NETTOOLKIT,;t t
+s,@DISABLE_ACTIVEX@,$DISABLE_ACTIVEX,;t t
 s,@ENABLE_RPATH@,$ENABLE_RPATH,;t t
 s,@WITH_MYSPELL_DICTS@,$WITH_MYSPELL_DICTS,;t t
 s,@USE_SHELL@,$USE_SHELL,;t t
