CWS-TOOLING: integrate CWS qadev34 2008-11-24 12:04:37 +0100 cn  r264220 : #i96037 bugfix: remove superfluous exclamation mark 2008-11-20 20:52:21 +0100 cn  r264100 : #i95964 fixes for cygwin 2008-11-20 12:10:41 +0100 cn  r264040 : #i95964 replacesment for cwsquery modules 2008-11-10 10:29:48 +0100 cn  r263511 : #i96037 register installoffice.oxt 2008-11-07 15:44:58 +0100 cn  r263423 : #i95964# changes for 'cwstouched' wihch is a replacemant for 'cwsquery modules' 2008-10-31 14:04:47 +0100 cn  r262866 : #i95303# add XDEBUG variable 2008-10-31 14:03:39 +0100 cn  r262865 : #i95610# update lists 2008-10-31 09:47:27 +0100 cn  r262855 : #i95303# bugfix 2008-10-31 09:47:06 +0100 cn  r262854 : #i95303# bugfix 2008-10-30 21:42:14 +0100 cn  r262837 : #i95204 remove -OOO_EnvSet parameter 2008-10-30 21:33:18 +0100 cn  r262836 : #i95304 add -enableautomation as soffice parameter 2008-10-30 10:20:24 +0100 cn  r262822 : #i95610 update lists 2008-10-27 22:00:00 +0100 cn  r262691 : #i95513#: add support for -runnerini as aditional ini file 2008-10-27 21:35:17 +0100 cn  r262690 : #i95513# use -runnerini instead of -ini 2008-10-23 13:41:32 +0200 cn  r262621 : #i95303# changes to run cwscheckapi in cygwin environment 2008-10-22 10:18:36 +0200 cn  r262581 : #i95304# disable QuckStarter while trying to dispose the office 2008-10-22 09:59:39 +0200 cn  r262580 : #i95303# add cygwin related stuff 2008-10-22 09:59:10 +0200 cn  r262579 : #i95303# add cygwin related stuff 2008-10-22 09:57:40 +0200 cn  r262578 : #i95303# add property CYGWIN

diff --git a/solenv/bin/cwscheckapi b/solenv/bin/cwscheckapi
--- a/solenv/bin/cwscheckapi
+++ b/solenv/bin/cwscheckapi
@@ -161,22 +161,45 @@ if [ $INSTALL = true ]; then
 	echo "`date` installation successfull, start testing...." 
 fi
 
-if [ $DEBUG_T = true ]; then
-    echo find $LOCALINSTALLDIR -name soffice
+SOFFICE="soffice"
+PS=":"
+CYGWIN=""
+
+SHELL="/bin/bash"
+# cygwin:
+if [ "$GUI" = "WNT" ]; then
+    SOFFICE="soffice.exe"
+    PS=";"
+    CYGWIN="-Cygwin true"
+    SHELL=`which bash`
+    SHELL=`cygpath -w $SHELL`
+    if [ ! -f $SHELL ]; then
+        echo "could not determine bash shell" 
+        exit 1
+    fi
 fi
 
-OFFICEBIN=`find $LOCALINSTALLDIR -name soffice`
+if [ $DEBUG_T = true ]; then
+    echo find $LOCALINSTALLDIR -name $SOFFICE
+fi
+
+OFFICEBIN=`find $LOCALINSTALLDIR -name $SOFFICE`
 
 if [ ! -f "$OFFICEBIN" ]; then
-    echo "could not find 'soffice' in subfolders of $LOCALINSTALLDIR";
+    echo "could not find 'soffice' in subfolders of $LOCALINSTALLDIR"
     exit 1
+fi
+
+if [ "$GUI" = "WNT" ]; then
+    # transform /tmp/... -> c:\tmp\...
+    OFFICEBIN=`cygpath -w $OFFICEBIN`
 fi
 
 JARFOLDER=$SOLARVERSION/$INPATH/bin$UPDMINOREXT
 SOLVER_LIB=$SOLARVERSION/$INPATH/lib$UPDMINOREXT
-myCLASSPATH=$JARFOLDER/OOoRunner.jar:$JARFOLDER/ridl.jar:$JARFOLDER/unoil.jar:$JARFOLDER/jurt.jar:$JARFOLDER/juh.jar:$JARFOLDER/java_uno.jar
-myCLASSPATH=$myCLASSPATH:$JARFOLDER/ridl.jar:$JARFOLDER/unoil.jar:$JARFOLDER/jurt.jar:$JARFOLDER/juh.jar:$JARFOLDER/java_uno.jar
-myCLASSPATH=$myCLASSPATH:/net/unoapi/export/unoapi/bin/mysql.jar:$SOLVER_LIB
+myCLASSPATH=${PS}${JARFOLDER}/ridl.jar${PS}${JARFOLDER}/unoil.jar${PS}${JARFOLDER}/jurt.jar${PS}${JARFOLDER}/juh.jar${PS}${JARFOLDER}/java_uno.jar
+myCLASSPATH=$myCLASSPATH${PS}${JARFOLDER}/OOoRunner.jar
+myCLASSPATH=$myCLASSPATH${PS}/net/unoapi/export/unoapi/bin/mysql.jar${PS}$SOLVER_LIB
 PARAM=""
 if [ -n "$JAVAI" ]; then
         JAVABIN=$JAVAI
@@ -202,13 +225,13 @@ if [ -n "$WORK_STAMP" ]; then
 	fi
 fi
 
-PARAM="$PARAM -cmd '$OFFICEBIN  -nofirststartwizard -norestore -nocrashreport -nolockcheck -accept=pipe,name=$USER;urp;'"
+PARAM="$PARAM -cmd '$OFFICEBIN -nofirststartwizard -accept=pipe,name=$USER;urp; -norestore -nocrashreport -nolockcheck -enableautomation'"
 PARAM="$PARAM -cs pipe,name=$USER"
 PARAM="$PARAM -NoOffice true"
-PARAM="$PARAM -OOO_EnvSet setsolar"
 PARAM="$PARAM -SRC_ROOT $SRC_ROOT"
 PARAM="$PARAM -COMP_ENV $OUTPATH"
-PARAM="$PARAM -Shell /bin/tcsh"
+PARAM="$PARAM -Shell $SHELL"
+PARAM="$PARAM $CYGWIN"
 PARAM="$PARAM -tb java_complex"
 PARAM="$PARAM -TimeOut 90000"
 PARAM="$PARAM -o complex.unoapi.CheckModuleAPI::module($MODULES)"
