INTEGRATION: CWS kendy05 (1.5.80); FILE MERGED 2005/04/08 13:34:34 kendy 1.5.80.3: Issue number: #i47021# Submitted by: kendy "env" script renamed to "ooenv" not to be confused with /usr/bin/ooenv. 2005/04/08 13:15:13 kendy 1.5.80.2: Issue number: #i47021# Submitted by: kendy We should ask pkg-config about the Mozilla libraries location, otherwise it breaks with system Mozilla. 2005/04/08 11:41:10 kendy 1.5.80.1: Issue number: #i45071# Submitted by: mmeeks This patch allows one to run linkoo multiple times without trouble & yet still doesn't screw up the recent files implementation.

diff --git a/solenv/bin/linkoo b/solenv/bin/linkoo
--- a/solenv/bin/linkoo
+++ b/solenv/bin/linkoo
@@ -12,9 +12,9 @@
 #
 #   $RCSfile: linkoo,v $
 #
-#   $Revision: 1.5 $
+#   $Revision: 1.6 $
 #
-#   last change: $Author: hr $ $Date: 2005-02-11 15:23:57 $
+#   last change: $Author: hr $ $Date: 2005-04-11 08:58:17 $
 #
 #   The Contents of this file are made available subject to the terms of
 #   either of the following licenses
@@ -67,13 +67,13 @@
 #
 #*************************************************************************
 
-# ends up in program/env
+# ends up in program/ooenv
+( $moz_lib = `pkg-config --variable=libdir mozilla-nss` ) =~ tr/\n/:/;
 $env_script = '
 java_path=`./javaldx`
-export LD_LIBRARY_PATH=".:$java_path:$LD_LIBRARY_PATH"
+export LD_LIBRARY_PATH=".:$java_path:' . $moz_lib . '$LD_LIBRARY_PATH"
 ulimit -c unlimited
 export PATH=".:$PATH"
-export LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH"
 export GNOME_DISABLE_CRASH_DIALOG=1
 export STAR_RESOURCEPATH=`pwd`/resource
 ';
@@ -238,13 +238,24 @@ sub scan_and_link_files($$$)
     print "\n";
 }
 
-sub fixup_evilness
+sub evilness($)
 {
+    my $doit = shift;
     my $name = 'librecentfile.so';
-    my $src = "$OOO_BUILD/shell/$TARGET/lib/$name";
-    if (-f $src) {
-	print " link $name\n";
-	symlink $src, "$OOO_BUILD/sfx2/$TARGET/lib/$name";
+    my $src  = "$OOO_BUILD/shell/$TARGET/lib/$name";
+    my $dest = "$OOO_BUILD/sfx2/$TARGET/lib/$name";
+
+    if ($doit eq 'undo') {
+	if (-l $dest) {
+	    print " unlink $name\n";
+	    unlink $dest;
+	}
+    } else {
+	$doit eq 'do' || die;
+        if (-f $src) {
+	    print " link $name\n";
+	    symlink $src, $dest;
+	}
     }
 }
 
@@ -290,6 +301,8 @@ substr ($OOO_BUILD, 0, 1)   eq '/' || die "linkoo requires absolute paths";
 
 ($TARGET, $LIBVER, $LANG, $DLLSUFFIX) = sniff_target ($OOO_BUILD);
 
+evilness ('undo');
+
 my $installed_files = build_installed_list ($OOO_INSTALL);
 
 scan_and_link_files ($OOO_BUILD, $installed_files, $TARGET);
@@ -304,11 +317,11 @@ if (-l $ooo_res && -l $star_res) {
 }
 print "\n";
 
-if (!-f "$OOO_INSTALL/program/env") {
-    print "Creating '$OOO_INSTALL/program/env'\n";
-    open ($env, ">$OOO_INSTALL/program/env") || die "Can't open $OOO_INSTALL/program/env: $!";
-    print $env $env_script;
-    close ($env);
+if (!-f "$OOO_INSTALL/program/ooenv") {
+    print "Creating '$OOO_INSTALL/program/ooenv'\n";
+    open ($ooenv, ">$OOO_INSTALL/program/ooenv") || die "Can't open $OOO_INSTALL/program/ooenv: $!";
+    print $ooenv $env_script;
+    close ($ooenv);
 }
 
-fixup_evilness();
+evilness ('do');
