resync to trunk (close to AOO400)

diff --git a/solenv/bin/macosx-create-bundle b/solenv/bin/macosx-create-bundle
--- a/solenv/bin/macosx-create-bundle
+++ b/solenv/bin/macosx-create-bundle
@@ -74,12 +74,12 @@ while [ $# != 0 ]; do
 	filetype=`file -L "$inputfile"`
 
 	# Create bundle based on file type
-	if printf "$filetype" | grep -q 'Mach-O executable'; then
+	if printf "$filetype" | grep -q 'Mach-O.* executable'; then
 
 		# Do nothing as this step is obsolete
         :
 
-	elif printf "$filetype" | grep -q 'Mach-O dynamically linked shared library'; then
+	elif printf "$filetype" | grep -q 'Mach-O.* dynamically linked shared library'; then
 		# Screen out lib\w+static libraries as they are not used directly
 		if ! printf "$inputfilename" | grep -q -x -E 'lib\w+static.*\.dylib'; then
 			# Create jnilib link
@@ -93,7 +93,7 @@ while [ $# != 0 ]; do
 			#printf "macosx-create-bundle: $outputdir/$inputjnilibname successfully created\n"
 		fi
 	else
-		printf "macosx-create-bundle: error: file is not an executable or shared library.\n" >&2
+		printf "macosx-create-bundle: error: \"$inputfile\" is not an executable or shared library.\n" >&2
 		exit 1
 	fi
 done
